-- BCX initial schema. Review target project before applying.
create extension if not exists pgcrypto;
create type public.bcx_product_status as enum ('draft','active','deprecated','archived');
create type public.bcx_user_role as enum ('admin','editor','viewer');
create table public.bcx_categories (code text primary key check(code ~ '^[A-Z]{2,5}$'), label text not null unique, description text, created_at timestamptz not null default now());
create table public.bcx_greek_generations (id uuid primary key default gen_random_uuid(), name text not null, symbol text not null, ordinal smallint not null check(ordinal between 1 and 24), cycle integer not null default 1 check(cycle >= 1), created_at timestamptz not null default now(), unique(cycle,ordinal), unique(cycle,name));
create table public.bcx_profiles (user_id uuid primary key references auth.users(id) on delete cascade, display_name text, role public.bcx_user_role not null default 'viewer', created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.bcx_products (id uuid primary key default gen_random_uuid(), identifier text not null unique, name text not null, description text, category_code text not null references public.bcx_categories(code), greek_generation_id uuid not null references public.bcx_greek_generations(id), serial_number integer not null check(serial_number > 0), technical_version text not null default '1.0.0', status public.bcx_product_status not null default 'draft', owner_user_id uuid references auth.users(id) on delete set null, metadata jsonb not null default '{}'::jsonb, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(category_code,greek_generation_id,serial_number), check(identifier ~ '^BCX-[A-Z]{2,5}-[A-Z]+-[0-9]{3,}$'));
create table public.bcx_audit_logs (id bigint generated always as identity primary key, actor_user_id uuid references auth.users(id) on delete set null, action text not null, entity_type text not null, entity_id uuid, details jsonb not null default '{}'::jsonb, created_at timestamptz not null default now());
create index bcx_products_category_idx on public.bcx_products(category_code);
create index bcx_products_status_idx on public.bcx_products(status);
create index bcx_products_created_at_idx on public.bcx_products(created_at desc);
create index bcx_audit_logs_created_at_idx on public.bcx_audit_logs(created_at desc);
alter table public.bcx_categories enable row level security;
alter table public.bcx_greek_generations enable row level security;
alter table public.bcx_profiles enable row level security;
alter table public.bcx_products enable row level security;
alter table public.bcx_audit_logs enable row level security;
create policy "Authenticated users read categories" on public.bcx_categories for select to authenticated using(true);
create policy "Authenticated users read Greek generations" on public.bcx_greek_generations for select to authenticated using(true);
create policy "Users read own profile" on public.bcx_profiles for select to authenticated using(user_id=auth.uid());
create policy "Users update own profile" on public.bcx_profiles for update to authenticated using(user_id=auth.uid()) with check(user_id=auth.uid());
create policy "Authenticated users read products" on public.bcx_products for select to authenticated using(true);
create policy "Editors manage products" on public.bcx_products for all to authenticated using(exists(select 1 from public.bcx_profiles p where p.user_id=auth.uid() and p.role in ('admin','editor'))) with check(exists(select 1 from public.bcx_profiles p where p.user_id=auth.uid() and p.role in ('admin','editor')));
create policy "Admins manage categories" on public.bcx_categories for all to authenticated using(exists(select 1 from public.bcx_profiles p where p.user_id=auth.uid() and p.role='admin')) with check(exists(select 1 from public.bcx_profiles p where p.user_id=auth.uid() and p.role='admin'));
create policy "Admins manage Greek generations" on public.bcx_greek_generations for all to authenticated using(exists(select 1 from public.bcx_profiles p where p.user_id=auth.uid() and p.role='admin')) with check(exists(select 1 from public.bcx_profiles p where p.user_id=auth.uid() and p.role='admin'));
create policy "Admins read audit logs" on public.bcx_audit_logs for select to authenticated using(exists(select 1 from public.bcx_profiles p where p.user_id=auth.uid() and p.role='admin'));
insert into public.bcx_categories(code,label,description) values ('AI','Intelligence artificielle','Produits et services IA'),('APP','Applications','Applications mobiles et desktop'),('WEB','Sites et plateformes web','Sites, portails et plateformes'),('SYS','Systèmes','Systèmes logiciels et infrastructures'),('SEC','Sécurité numérique','Produits de cybersécurité'),('LAB','Recherche et expérimentation','Prototypes, R&D et expérimentations') on conflict(code) do nothing;
insert into public.bcx_greek_generations(name,symbol,ordinal,cycle) values ('ALPHA','Α',1,1),('BETA','Β',2,1),('GAMMA','Γ',3,1),('DELTA','Δ',4,1),('EPSILON','Ε',5,1),('ZETA','Ζ',6,1),('ETA','Η',7,1),('THETA','Θ',8,1),('IOTA','Ι',9,1),('KAPPA','Κ',10,1),('LAMBDA','Λ',11,1),('MU','Μ',12,1),('NU','Ν',13,1),('XI','Ξ',14,1),('OMICRON','Ο',15,1),('PI','Π',16,1),('RHO','Ρ',17,1),('SIGMA','Σ',18,1),('TAU','Τ',19,1),('UPSILON','Υ',20,1),('PHI','Φ',21,1),('CHI','Χ',22,1),('PSI','Ψ',23,1),('OMEGA','Ω',24,1) on conflict(cycle,ordinal) do nothing;
